### ISSUE TITLE
Missing sqrt?

### ISSUE THREAD

**Issue by ajaymur91** [LongyuanZhang/OMM_GMX#1]
https://github.com/LongyuanZhang/OMM_GMX/blob/297f7e7d7605223db3266b08e2556ce0e6b5e90b/ti.py#L66

Is there a missing sqrt?

**Comment by LongyuanZhang** [comment]
If we run these codes:
```
parm = parmed.load_file("tmp.top",xyz="solv_ions.gro")
positions = parm.positions
#print(type(parm))
system = parm.createSystem(nonbondedMethod=PME, nonbondedCutoff=1*nanometers, constraints=HBonds, rigidWater=True, ewaldErrorTolerance=0.0005)

forces = system.getForces()
for force in forces:
    if type(force) is NonbondedForce:
        force.setUseDispersionCorrection(True)
        nonbondedforce = force
        break

# comb_rule = 3 leads to a ParmEd defined customNB == nonbonded LJ
for force in forces:
    if type(force) is CustomNonbondedForce:
        #force.setUseLongRangeCorrection(True)
        CustomLJbyParmed = force
        break

print(CustomLJbyParmed.getEnergyFunction())
```
, we will get
`epsilon1*epsilon2*(sigr6^2-sigr6); sigr6=sigr2*sigr2*sigr2; sigr2=(sigc/r)^2; sigc=sigma1*sigma2`
There isn't a sqrt for sigma or epsilon, which I believe comes from how ParmEd "translates" comb_rule = 3. I also think that the sigma1 and sigma2 in this CustomLJbyParmed don't have the same sigma values as in OPLS-AA. Epsilons as well.
