### ISSUE TITLE
Suggestion: Include env.yaml for easy conda installation

### ISSUE THREAD

**Issue by ajaymur91** [LongyuanZhang/OMM_GMX#2]
Some of the openmm functions don't work because I am using a different (perhaps slightly older) version of openmm. It would be nice if we include an env.yaml file that can be used to install exact version of openmm and parmed that was used here.

**Comment by LongyuanZhang** [comment]
Good idea, I will do that.

**Comment by LongyuanZhang** [comment]
I added OMM_GMX.yml just now.
